### ISSUE TITLE
Truth/Desire Function argument swapping for swapped rules.

### ISSUE THREAD

**Issue by patham9** [opennars/opennars2#27]
As we know from the rule
A, B |- C
we can (according to our conditions) sometimes derived
B, A |- C
this also seems to be done already, however altough the premises are swapped, the arguments of the truth function are not, causing mistakes.

**Comment by rasom** [comment]
@patham9, can you give some specific example of rule that derives wrong results?

**Comment by rasom** [comment]
https://gist.github.com/rasom/dc1ef3fd00509b35781502d7c58784bd
https://gist.github.com/rasom/3f9ec4fa906fdc2d42ffd25083d300b0

Which conclusions are wrong in these examples ?

**Comment by patham9** [comment]
```
(deftest nal1-inheritance-related-syllogisms-abduction
  (is (derived "<sport --> competition>."
               "<chess --> competition>. %0.90;0.90%"
               ["<sport --> chess>. %1.00;0.42%"
                "<chess --> sport>. %0.90;0.45%"])))

(deftest nal1-inheritance-related-syllogisms-induction
  (is (derived "<swan --> swimmer>. %0.90;0.90%"
               "<swan --> bird>."
               ["<bird --> swimmer>. %0.90;0.45%"
                "<swimmer --> bird>. %1.00;0.42%"])))
```

In both cases it uses the same truth value altough the second case is the swapped case, where as I said, the truth function arguments are not swapped also, and thus it fails both tests.

**Comment by patham9** [comment]
```
(conclusions "<sport --> competition>." "<chess --> competition>. %0.90;0.90%")
=>
#{{:statement [--> chess sport], :task-type :belief, :occurrence 0, :truth [0.9 0.44751381215469616]}
  {:statement [--> sport chess], :task-type :belief, :occurrence 0, :truth [0.9 0.44751381215469616]}
  ...}
```

See? Same truth value, truth function arguments were not swapped for the swapped rule!

**Comment by patham9** [comment]
Issue resolved by my commit in Patrick_General_Inference_Tasks. Closed.
