### ISSUE TITLE
Parser exception for single term sentence

### ISSUE THREAD

**Issue by TonyLo1** [opennars/opennars2#43]
Following Narsese causes exception: <jump>!

This functionality is required for goals.

**Comment by jarradh** [comment]
whats the statement in this case? atm the grammar doesn't handle a sentence with empty statement?

https://github.com/jarradh/narjure/blob/master/resources/narsese.bnf#L8

could be changed to 
`| [statement]"!" [tense] [desire]`

**Comment by TonyLo1** [comment]
oh, the statement was removed :)

Should have said: `<jump>!`

**Comment by patham9** [comment]
No! This is not a statement. Don't update the parser for this please!! jump! not <jump>!. As I said NAL is complete just look at the NAL test file to see how enter statements properly ;)
