### ISSUE TITLE
Add input-load-reducer

### ISSUE THREAD

**Issue by TonyLo1** [opennars/opennars2#47]
This is slightly more problematic than derived-load-reducer as there may not be a budget available for the bag sort order.

Currently input budget is ignored by task-creator and default is assigned. maybe budget should be assigned at sentence parsing or input sensor?

**Comment by patham9** [comment]
budget is aviable after parse2 already so I don't see the issue here.

**Comment by TonyLo1** [comment]
ok, great - when you wrote task-creator, you reset the budget to default

**Comment by patham9** [comment]
Oh sorry, can just use the budget which is already in. ^^
