### ISSUE TITLE
Mailbox issue

### ISSUE THREAD

**Issue by patham9** [opennars/opennars2#48]
We still don't have the message flow under control, how is it that 30 seconds after (stop) the system still processes messages and then stops?

We have to add a timer tick in load reducer as I suggested at first in order to control the messages forwarded to task dispatcher per time, else this won't change probably.

**Comment by TonyLo1** [comment]
You have to tune the parameters for your system. It's likely that params are too high for the processing power you have available.

You need to reduce the number of selections per cycle in concept-selector and load-reducer. load-reducer already uses a timer-tick.

**Comment by TonyLo1** [comment]
Another issue is that bag is really slow

**Comment by patham9** [comment]
this is fine for now. ^^

2016-06-05 19:14 GMT+02:00 TonyLo1 <notifications@github.com>:

**Comment by patham9** [comment]
How can I access task state if I have an actor ref?

**Comment by TonyLo1** [comment]
You can't. Actor state can only be accessed within an actor - this is by design.

**Comment by patham9** [comment]
so how can I ask the actor about the task bag state if I have the actor ref? I just need read access.

**Comment by patham9** [comment]
will just reference the task bag into a atom dictionary whenever the actor processes a message, this way no copy of state happens (only if debug/Lense is true of course), and when we move to multiple machines we will need a more sophisticated Lense anyway.

**Comment by patham9** [comment]
closed since slower amount of concept selection param per cycle as Tony pointed out solved it for me.
