### ISSUE TITLE
Restart issue

### ISSUE THREAD

**Issue by patham9** [opennars/opennars2#50]
Some actors sometimes hamper a warm-restart, mainly the general_inferencer:

07:22:50.238 WARN  [co.paralleluniverse.actors.behaviors.SupervisorActor] (ForkJoinPool-default-fiber-pool-worker-13) Child Server{ActorRef@6ee2795c{ServerActor@general-inferencer[owner: fiber-10000889]}} shutdown timeout. Interrupting...
07:22:50.339 WARN  [co.paralleluniverse.actors.behaviors.SupervisorActor] (ForkJoinPool-default-fiber-pool-worker-13) Child Server{ActorRef@6ee2795c{ServerActor@general-inferencer[owner: fiber-10000889]}} could not shut down...

**Comment by TonyLo1** [comment]
yes, not sure why yet. if you repeat the, stop, shutdown, restart sequence it generally clears it.

I will look into this when I have more time.

**Comment by patham9** [comment]
works nicely since quite some time already.
