### ISSUE TITLE
deriver reduction rule for &/ needs reviewing

### ISSUE THREAD

**Issue by TonyLo1** [opennars/opennars2#53]
There are nested &/ derivations appearing

**Comment by patham9** [comment]
indeed, but I hesitated so far since the nested representation provides benefits for reasoning, for example this way (&/,a,operation) is a very general form where a could be a sequence on its own as especially needed by our new operation-choice rule.

**Comment by patham9** [comment]
TODO re-consider in the future, closed because for now I think the nested representation is better for the reason explained.
