### ISSUE TITLE
Potential sources of a memory leak

### ISSUE THREAD

**Issue by rasom** [opennars/opennars2#54]
https://github.com/opennars/opennars2/blob/2_0_3_simple_budget/src/nal/deriver.clj#L21
https://github.com/opennars/opennars2/blob/0a20811d218934fce5d7fc256b2f682d1c35eb88/src/nal/deriver.clj#L22
https://github.com/opennars/opennars2/blob/0a20811d218934fce5d7fc256b2f682d1c35eb88/src/nal/deriver/key_path.clj#L48
https://github.com/opennars/opennars2/blob/0a20811d218934fce5d7fc256b2f682d1c35eb88/src/nal/deriver/key_path.clj#L58
https://github.com/opennars/opennars2/blob/0a20811d218934fce5d7fc256b2f682d1c35eb88/src/nal/deriver/substitution.clj#L21

If you will find a problem here, there is `core.memoize` https://github.com/clojure/core.memoize/ library which provides different strategies for cache invalidation.

**Comment by patham9** [comment]
thanks a lot! :)

**Comment by patham9** [comment]
this was indeed the source of the memory leak as you thought, and since we resolved it: closed.
