### ISSUE TITLE
Lein Marginalia failure

### ISSUE THREAD

**Issue by jorisbontje** [opennars/opennars2#55]
Doing the binary search for `lein marg` first failure:
```
dcf168dd5807d285d9cecd3ac99fa192adc1981e is the first bad commit
```
Full git bisect log: https://gist.github.com/jorisbontje/90bf0ce0aee30c84ab16e3653ffbf5a5

This seems to be the offending line currently causing `lein marg` to fail: https://github.com/opennars/opennars2/blob/2_0_3_simple_budget/src/narjure/memory_management/task_dispatcher.clj#L86

(found by creating a local copy of marginalia, with a `println` in the `parse-file` function)

**Comment by patham9** [comment]
Wow thank you!!! :)
This really helps us a lot as we consider good documentation for this project as crucial,

Best regards.
Patrick

**Comment by patham9** [comment]
Wow thank you!!! :)
This really helps us a lot as we consider good documentation for this project as crucial,

Best regards.
Patrick

**Comment by patham9** [comment]
Wow thank you!!! :)
This really helps us a lot as we consider good documentation for this project as crucial,

Best regards.
Patrick

**Comment by patham9** [comment]
Indeed this keyword :event-buffer shouldn't even be there.
It works now, the documentation will be updated with next commit and further refined in the next days, thank you again for finding the issue, jorisbontje! :)
