### ISSUE TITLE
Question about proposed setup

### ISSUE THREAD

**Issue by sammyboy45467** [opennars/opennars2#60]
New to NARS, looking for direction on setup, environment specifications and if possible minimum requirements. I've been trying to run on unix environments with little success. For some reason I can't open the GUI when using `lein repl`.

**Comment by patham9** [comment]
for newcomers supported way: Download the release package, make sure java8
is installed, then run the start script. For running it in the IDE, run the
-main of lense.clj. If you fail here read Cursive/IntelliJ IDE tutorials,
wait for future Wiki extensions, or tell us where you are stuck. Best
regards, Patrick

**Comment by sammyboy45467** [comment]
Thanks that is very helpful! Looking forward to the future of this project!
